/**
 * Runs once locally to compute embeddings for each knowledge base chunk.
 * Usage:
 *   set OPENAI_API_KEY=sk-...
 *   node scripts/build_kb.mjs
 *
 * Output: netlify/functions/kb.mjs  (committed to repo, bundled by esbuild on deploy)
 */

import OpenAI from 'openai';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

const apiKey = process.env.OPENAI_API_KEY;
if (!apiKey) {
  console.error('OPENAI_API_KEY environment variable is not set.');
  process.exit(1);
}

const client = new OpenAI({ apiKey });

const contentPath = join(rootDir, 'knowledge_base_content.json');
const { chunks } = JSON.parse(readFileSync(contentPath, 'utf-8'));

console.log(`Computing embeddings for ${chunks.length} chunks...`);

const embedded = [];
for (const chunk of chunks) {
  const res = await client.embeddings.create({
    model: 'text-embedding-3-small',
    input: chunk.content,
  });
  embedded.push({ ...chunk, embedding: res.data[0].embedding });
  console.log(`  [OK] ${chunk.title}`);
}

const outDir = join(rootDir, 'netlify', 'functions');
mkdirSync(outDir, { recursive: true });

const outPath = join(outDir, 'kb.mjs');
const js = `// Auto-generated by scripts/build_kb.mjs — do not edit manually.
// Re-run the script after updating knowledge_base_content.json.
export const chunks = ${JSON.stringify(embedded, null, 2)};
`;
writeFileSync(outPath, js, 'utf-8');

console.log(`\nKnowledge base written to netlify/functions/kb.mjs`);
console.log('Deploy the site to Netlify to activate the chatbot.');
